/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_nyiit_heartbeat_detector_FaceDetector */

#ifndef _Included_com_nyiit_heartbeat_detector_FaceDetector
#define _Included_com_nyiit_heartbeat_detector_FaceDetector
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_nyiit_heartbeat_detector_FaceDetector
 * Method:    FaceDetectionModelInit
 * Signature: (Ljava/lang/String;)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nyiit_heartbeat_detector_FaceDetector_FaceDetectionModelInit
  (JNIEnv *, jobject, jstring);

/*
 * Class:     com_nyiit_heartbeat_detector_FaceDetector
 * Method:    FaceDetect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nyiit_heartbeat_detector_FaceDetector_FaceDetect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nyiit_heartbeat_detector_FaceDetector
 * Method:    MaxFaceDetect
 * Signature: (J)V
 */
JNIEXPORT void JNICALL Java_com_nyiit_heartbeat_detector_FaceDetector_MaxFaceDetect
  (JNIEnv *, jobject, jlong);

/*
 * Class:     com_nyiit_heartbeat_detector_FaceDetector
 * Method:    FaceDetectionModelUnInit
 * Signature: ()Z
 */
JNIEXPORT jboolean JNICALL Java_com_nyiit_heartbeat_detector_FaceDetector_FaceDetectionModelUnInit
  (JNIEnv *, jobject);

/*
 * Class:     com_nyiit_heartbeat_detector_FaceDetector
 * Method:    SetMinFaceSize
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nyiit_heartbeat_detector_FaceDetector_SetMinFaceSize
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nyiit_heartbeat_detector_FaceDetector
 * Method:    SetThreadsNumber
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nyiit_heartbeat_detector_FaceDetector_SetThreadsNumber
  (JNIEnv *, jobject, jint);

/*
 * Class:     com_nyiit_heartbeat_detector_FaceDetector
 * Method:    SetTimeCount
 * Signature: (I)Z
 */
JNIEXPORT jboolean JNICALL Java_com_nyiit_heartbeat_detector_FaceDetector_SetTimeCount
  (JNIEnv *, jobject, jint);

#ifdef __cplusplus
}
#endif
#endif
